GET http://127.0.0.1:8080/api/todos

### 

POST http://127.0.0.1:8080/api/todos
Content-Type: application/json

{
    "body" : "Learn Svelte",
    "completed" : false
}

###

PATCH http://127.0.0.1:8080/api/todos/6a51304fa3eddbbce2791249

###

DELETE http://127.0.0.1:8080/api/todos/6a511692703c61c95dfe4070
